steps:
  # npm install
  - name: node:16.19.1
    entrypoint: yarn
    id: nuxt-install
    args: ["install", "--frozen-lockfile"]
    dir: "./src/nuxt"
  # run build
  - name: node:16.19.1
    entrypoint: yarn
    id: nuxt-build
    args: ["run", "build"]
    dir: "./src/nuxt"
  # Deploy to App Engine
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-app
    args: ["app", "deploy", "app.yaml", "-v", "prod"]
    dir: "./src/nuxt"
